/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrincipalMessageRouteImport } from './routes/principal-message'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalMessageRoute = PrincipalMessageRouteImport.update({
  id: '/principal-message',
  path: '/principal-message',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/admissions': typeof AdmissionsRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admissions'
    | '/classes'
    | '/contact'
    | '/events'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/news'
    | '/principal-message'
    | '/sitemap.xml'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admissions'
    | '/classes'
    | '/contact'
    | '/events'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/news'
    | '/principal-message'
    | '/sitemap.xml'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/admissions'
    | '/classes'
    | '/contact'
    | '/events'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/news'
    | '/principal-message'
    | '/sitemap.xml'
    | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PrincipalMessageRoute: typeof PrincipalMessageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal-message': {
      id: '/principal-message'
      path: '/principal-message'
      fullPath: '/principal-message'
      preLoaderRoute: typeof PrincipalMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionsRoute: AdmissionsRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PrincipalMessageRoute: PrincipalMessageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
